#!/bin/bash
            version=$(/home/wasim/.config/neo4j-desktop/Application/Data/dbmss/dbms-7b86e292-488a-4cde-9558-e3a5347f24fc/bin/neo4j-admin --version | cut -d '.' -f 1)
            echo "Neo4j detected version: $version" >&2
            # If Neo4j's version < 5.
            if [[ $version -lt 5 ]] ; then
                # Old interface.
                /home/wasim/.config/neo4j-desktop/Application/Data/dbmss/dbms-7b86e292-488a-4cde-9558-e3a5347f24fc/bin/neo4j-admin import --database=neo4j --delimiter="	" --array-delimiter=";" --quote='"' --force=true --skip-bad-relationships=true --skip-duplicate-nodes=true --nodes="/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Protein-header.csv,/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Protein-part.*" --relationships="/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Inhibition-header.csv,/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Inhibition-part.*" --relationships="/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Activation-header.csv,/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Activation-part.*" --relationships="/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Binding-header.csv,/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Binding-part.*" --relationships="/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Ubiquitination-header.csv,/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Ubiquitination-part.*" --relationships="/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Phosphorylation-header.csv,/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Phosphorylation-part.*" 
            else
                # New interface.
                /home/wasim/.config/neo4j-desktop/Application/Data/dbmss/dbms-7b86e292-488a-4cde-9558-e3a5347f24fc/bin/neo4j-admin database import full neo4j --delimiter="	" --array-delimiter=";" --quote='"' --overwrite-destination=true --skip-bad-relationships=true --skip-duplicate-nodes=true --nodes="/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Protein-header.csv,/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Protein-part.*" --relationships="/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Inhibition-header.csv,/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Inhibition-part.*" --relationships="/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Activation-header.csv,/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Activation-part.*" --relationships="/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Binding-header.csv,/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Binding-part.*" --relationships="/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Ubiquitination-header.csv,/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Ubiquitination-part.*" --relationships="/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Phosphorylation-header.csv,/home/wasim/Desktop/BioCypher_WS/BCWorkshop-Tutorial-Knowledge-Graph/biocypher-out/Phosphorylation-part.*" 
            fi
        